---
#---------------------------
# Hexo Theme Fluid
# Author: Fluid-dev
# Github: https://github.com/fluid-dev/hexo-theme-fluid
#
# 配置指南: https://hexo.fluid-dev.com/docs/guide/
# 你可以从指南中获得更详细的说明
#
# Guide: https://hexo.fluid-dev.com/docs/en/guide/
# You can get more detailed help from the guide
#---------------------------

# 浏览器标签页中的标题分隔符，效果： 文章名 - 站点名
tab_title_separator: " | "

# 强制所有链接升级为 HTTPS（适用于图片等资源出现 HTTP 混入报错）
force_https: true

# Code 塊
code:
    copy_btn: true
    highlight:
        enable: true
        line_number: true
        lib: "highlightjs"
        highlightjs:
            style: "atom-one-dark"
            bg_color: true

# Navbar
navbar:
    # Navbar Title
    blog_title: 白貓's blog

    # Navbar 菜單
    menu:
        - { key: "home", link: "/", icon: "iconfont icon-home-fill" }
        - {
              key: "存檔",
              link: "/archives/",
              icon: "iconfont icon-archive-fill",
          }
        - {
              key: "category",
              link: "/categories/",
              icon: "iconfont icon-category-fill",
          }
        - { key: "tag", link: "/tags/", icon: "iconfont icon-tags-fill" }
        - { key: "about", link: "/about/", icon: "iconfont icon-user-fill" }
        - {
              key: "Link Tree",
              link: "https://link.whitecat.tk",
              icon: "iconfont icon-link-fill",
          }

# 自訂義 css
custom_css:
    - /css/mac.css
    - /css/font.css

# 主頁面
index:
    banner_img: https://i.pinimg.com/originals/de/c0/e1/dec0e1d86817d93e3a89b4f25cb15ab7.jpg
    slogan:
        enable: true
        text: Welcome To WhiteCat's Blog
    post_meta:
        date: true
        category: true
        tag: true
    auto_excerpt:
        enable: true

# 關於頁
about:
    avatar: /images/WhiteCat.png
    name: "白貓"
    intro: "遊戲愛好者 / 前端實習工 / 成電弱神"
    icons:
        - {
              class: "iconfont icon-instagram-fill",
              link: "https://www.instagram.com/whitecatstudy/",
              tip: "Instagram",
          }
        - {
              class: "iconfont icon-github-fill",
              link: "https://github.com/CuteWhiteCat",
              tip: "Github",
          }
        - {
              class: "iconfont icon-mail",
              link: "mailto:awacutewhitecat@gmail.com",
              tip: "寄郵件",
          }

# 存檔頁
archive:
    banner_img: https://c0.wallpaperflare.com/preview/423/1002/349/plant-leaf-aquatic-water.jpg
    banner_img_height: 60
    banner_mask_alpha: 0.3

# 分類頁
category:
    enable: true
    banner_img: https://i.pinimg.com/originals/97/85/1f/97851f8076c6b29ed2cbb446dead2eb6.jpg
    banner_img_height: 60
    banner_mask_alpha: 0.6

# 標籤頁
tag:
    enable: true
    banner_img: https://images.unsplash.com/photo-1526925210199-6db37fd596af?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8c2t5JTIwaGlnaHxlbnwwfHwwfHw%3D&w=1000&q=80
    banner_img_height: 60
    banner_mask_alpha: 0.5
    tagcloud:
        min_font: 15
        max_font: 30
        unit: px
        start_color: "#BBBBEE"
        end_color: "#337ab7"

# 字體
font: 
    font_size: 16px 
    font_family: AppleGothic 
    code_font_size: 85%

# 日期/字數/閱讀時長/閱讀數
post:
    meta:
        author: 
            enable: true
        date: 
            enable: true
            format: "LL a" 
        wordcount: 
            enable: true
            format: "{} 字" 
        min2read: 
            enable: true
            format: "{} 分鐘"
        views: 
            enable: false
            source: "leancloud" 
            format: "{} 次"
    comments:
        enable: true
        type: utterances

# Utterances 評論插件
utterances:
    repo: CuteWhiteCat/blog-hexo
    issue_term: pathname
    label: #
    theme: github-light
    theme_dark: dark-blue


# Footer
footer:
  content: '
    <h6>WhiteCat © 2022 All rights reserved.</h6>
  '

