---
#---------------------------
# Hexo Theme Fluid
# Author: Fluid-dev
# Github: https://github.com/fluid-dev/hexo-theme-fluid
#
# 配置指南: https://hexo.fluid-dev.com/docs/guide/
# 你可以从指南中获得更详细的说明
#
# Guide: https://hexo.fluid-dev.com/docs/en/guide/
# You can get more detailed help from the guide
#---------------------------

#---------------------------
# 全局
# Global
#---------------------------

# 浏览器标签页中的标题分隔符，效果： 文章名 - 站点名
# Title separator in browser tab, eg: article - site
tab_title_separator: " | "

# 强制所有链接升级为 HTTPS（适用于图片等资源出现 HTTP 混入报错）
# Force all links to be HTTPS (applicable to HTTP mixed error)
force_https: true

# 代码块的增强配置
# Enhancements to code blocks
code:
    copy_btn: true
    highlight:
        enable: true
        line_number: true
        lib: "highlightjs"
        highlightjs:
            style: "atom-one-dark"
            bg_color: true

navbar:
    # 导航栏左侧的标题，为空则按 hexo config 中 `title` 显示
    # The title on the left side of the navigation bar. If empty, it is based on `title` in hexo config
    blog_title: 白貓's blog

    # 导航栏菜单，可自行增减，key 用来关联 languages/*.yml，如不存在关联则显示 key 本身的值；icon 是 css class，可以省略；增加 name 可以强制显示指定名称
    # Navigation bar menu. `key` is used to associate languages/*.yml. If there is no association, the value of `key` itself will be displayed; if `icon` is a css class, it can be omitted; adding `name` can force the display of the specified name
    menu:
        - { key: "home", link: "/", icon: "iconfont icon-home-fill" }
        - { key: "about", link: "/about/", icon: "iconfont icon-user-fill" }
        - {
              key: "Link Tree",
              link: "https://link.whitecat.tk",
              icon: "iconfont icon-link-fill",
          }
        - {
              key: "Github",
              link: "https://github.com/CuteWhiteCat",
              icon: "iconfont icon-github-fill",
          }

custom_css:
    - /css/mac.css
    - /css/font.css

# 主頁面
index:
    banner_img: https://i.pinimg.com/originals/de/c0/e1/dec0e1d86817d93e3a89b4f25cb15ab7.jpg
    slogan:
        enable: true
        text: Welcome To WhiteCat's Blog

# 字體
font:  # 主题字体配置
  font_size: 16px  # 全局字号
  font_family: AppleGothic  # 全局字体族
  code_font_size: 85%  # 代码的字号
